plantilla: &plantilla
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: cargocom
  password: cargocom
  port: 5432
  host: localhost


development:
  <<: *plantilla
  database: fosubo_development

test: &test
  <<: *plantilla
  database: fosubo_test

production:
  <<: *plantilla
  host: <%= ENV['DB_HOST'] %>
  database: fosubo
  username: <%= ENV['DB_USER'] %>
  password: <%= ENV['DB_PASS'] %>


cucumber:
  <<: *test
